### ISSUE TITLE
Event when clicking on the icon

### ISSUE THREAD

**Issue by mdings** [ssbc/forked-systray#10]
Is it possible to have an event that listens for a click on the icon itself? Instead of waiting for a click on one of the menu items below it.

**Comment by cryptix** [comment]
hey @mdings! 

First, sorry for the late reply. My github notifications are a mess.

> Is it possible to have an event that listens for a click on the icon itself?

The OS integration and  event creation happens in https://github.com/ssbc/systrayhelper so the feature needs to be added there first.

Since this is essentially the _menu opened_ event, I don't think it would be that hard to add.

Is this still relevant for you?

**Comment by mdings** [comment]
Oh that's alright. Thanks for looking into this.
It's not super duper relevant anymore but still a nice to have!
